title: Site

columns:
  - width: 1/3
    sections:
      albums: sections/albums
  - width: 1/3
    sections:
      # notes: sections/notes
      pages:
        type: pages
        create: default
        template:
          - NewPage
          - home
          - NewPage
          - default
  -width: 1/3
    sections:
      bref: sections/bref
